---
title: "Declan Bradley - Railstate Pitch"
output: html_document
date: "2025-06-02"
author: "Declan Bradley"
---

**Declan Bradley**, declanrjb@proton.me, (616) 914-9525

# Story Pitch

## Key Idea
The Association of American Railroads requires that trains carrying certain loads of hazardous material, referred to as "key trains," travel no faster than 50 mph. An analysis of car and train tables, cross-referenced with snapshots of travel speed at each track sensor, can identify instances of high risk cargoes traveling faster than 50 mph, in violation of this requirement.

## Relevance
The Trump administration has implemented cuts to oversight and enforcement across the federal government, making this story especially impactful in a time of increased risk for accidents in the air, at sea, and on the rails.

## Audience
Decision makers, legislators, and rail industry professionals could use these findings as a basis to step up enforcement of rail safety.

## Potential Interviews
- A train pilot or technician with experience transporting hazardous materials
- Officials involved in the NTSB (National Transportation Safety Board)
- Scientific experts on the specific materials found to be frequently moved at high speeds

## Potential Impact
It should be noted that this analysis is preliminary and may ultimately find no significant violations of regulation. However, if violations are found, they would be serious incidents that could sway public leaders to step up enforcement of safety regulations. Even if no key trains exceed the limit of 50 mph, hazardous materials might still found to be moving at high speeds, which could still be cause for concern to the public, especially if such speeds are detected in regions at high risk for derailments or accidents.

## Surprising Findings
The sheer number of cars classified as key or hazardous is striking. Even after filtering for cars not marked as empty, the data is still too large to process quickly. Additionally, many trains travel over the recommended limit, hitting 70 or 80 miles an hour, although I have not yet succeeded in identifying which of these are key trains. I found that certain hazardous materials tend to travel faster than others, which I have as yet no explanation for.

## Prior Coverage
In February 2023, a train derailment in East Palestine OH spilled hazardous materials including vinyl chloride into the surrounding land. The crash devastated the local community, and an ongoing cleanup effort has so far cost more than $800 million, according to [NPR reporting](https://www.npr.org/2024/02/05/1228772709/east-palestine-train-derailment-norfolk-southern-lawsuit-epa).

## Visuals
An interactive map can display sensor sites where hazardous trains were detected traveling at high speeds. The data already has lat long coordinates, so producing such a map should not be particularly time consuming. The story can also use images and videos from known crash sites such as the East Palestine derailment, although it will be important to clarify whether those crashes occurred under high speed conditions.

## Further Work
This analysis relies on the assumption that a trainId designates a specific journey and not a specific locomotive. That is to say, if a given trainId is carrying hazardous materials, it is carrying those materials at every sensor observation. If trains instead retain consistent IDs while loading and unloading cars it will be more difficult to guarantee that trains are violating safety codes. A train could, for example, detach its hazardous cars at one station, then accelerate before the next sensor, all without violating safety codes.

It is also worthy of note that the analysis is incomplete, and the code takes significant time to execute. More work will be needed to produce specific deliverable results.

## Estimated Delivery
The data is readily available, but analysis will take time. The most time consuming aspect of the project will be finding sources involved in the rail industry willing to speak on the record about these issues. To be cautious, I would estimate a project ready for review by an editor, if not immediate publication, would take until mid July.